import type { ThemeProviderTheme } from '@sohantalukder/rn-kit';

export const bloomColors = {
  brass: '#B98C42',
  cream: '#F3EFE4',
  danger: '#8A4038',
  errorBorder: '#E2C4BD',
  errorSurface: '#F7E9E5',
  errorText: '#7D3F38',
  forest: '#15382F',
  forestDeep: '#0C2520',
  ink: '#17211E',
  muted: '#5F6B65',
  pale: '#D9DFD1',
  paper: '#FBF8EF',
  restoreBorder: '#DDCFAE',
  restoreSurface: '#F5EEDB',
  restoreText: '#6F674F',
  rule: '#C8C1AE',
  storyRing: 'rgba(255,255,255,0.08)',
  storyRingSoft: 'rgba(255,255,255,0.05)',
  storyText: '#C5D4CC',
  success: '#315A49',
  successBorder: '#C7D8CE',
  successSurface: '#E7EFE9',
  white: '#FFFFFF',
} as const;

export const bloomTheme: ThemeProviderTheme = {
  colors: {
    background: bloomColors.cream,
    error: bloomColors.danger,
    gray0: bloomColors.ink,
    gray1: bloomColors.muted,
    gray2: '#6F7873',
    gray3: '#7F8882',
    gray4: '#929992',
    gray5: '#A8A99F',
    gray6: '#B9B6AA',
    gray7: bloomColors.rule,
    gray8: '#DDD8CA',
    gray9: '#ECE7DB',
    gray10: bloomColors.paper,
    placeholder: bloomColors.paper,
    placeholderBg: '#E5E0D4',
    primary: bloomColors.forest,
    ripple: bloomColors.forest,
    secondary: bloomColors.brass,
    success: bloomColors.success,
    text: bloomColors.ink,
    warning: bloomColors.brass,
    white: bloomColors.white,
  },
  navigationColors: {
    background: bloomColors.cream,
    border: bloomColors.rule,
    card: bloomColors.paper,
    notification: bloomColors.danger,
    primary: bloomColors.forest,
    text: bloomColors.ink,
  },
  variants: {
    dark: {
      colors: {
        background: bloomColors.forestDeep,
        gray0: bloomColors.paper,
        gray1: '#C5D4CC',
        gray7: '#3D5149',
        gray8: '#31463E',
        gray9: '#21372F',
        gray10: bloomColors.forestDeep,
        placeholder: bloomColors.forestDeep,
        placeholderBg: '#31463E',
        primary: '#F1C875',
        ripple: bloomColors.paper,
        secondary: '#D8B56E',
        text: bloomColors.paper,
      },
      navigationColors: {
        background: bloomColors.forestDeep,
        border: '#3D5149',
        card: '#102E27',
        notification: '#D9877E',
        primary: '#F1C875',
        text: bloomColors.paper,
      },
    },
  },
};

export const bloomFonts = {
  body: 'Manrope_400Regular',
  bodyBold: 'Manrope_700Bold',
  bodyMedium: 'Manrope_500Medium',
  bodySemibold: 'Manrope_600SemiBold',
  display: 'Newsreader_500Medium',
  displayItalic: 'Newsreader_500Medium_Italic',
} as const;
