/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habit-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHabitTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHabits"];
        put?: never;
        post: operations["createHabit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits/{habitId}/logs/{localDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["checkInHabit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/admin/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListTemplates"];
        put?: never;
        post: operations["adminCreateTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateTemplate"];
        trace?: never;
    };
    "/admin/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notifications/{deliveryId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRetryNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminCreateAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habit-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getHabitRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prayer-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrayerTimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prayers/{prayer}/logs/{localDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["checkInPrayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits/{habitId}/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateHabitReminder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerFirebaseInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/installations/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unregisterFirebaseInstallation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Liveness: {
            /** @constant */
            status: "ok";
            /** @constant */
            service: "smart-habit-api";
            /** Format: date-time */
            timestamp: string;
        };
        Readiness: {
            /** @constant */
            status: "ready";
            dependencies: {
                /** @constant */
                postgres: "ready";
                /** @constant */
                queue: "ready";
            };
            /** Format: date-time */
            timestamp: string;
        };
        SignupInput: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        EmailInput: {
            /** Format: email */
            email: string;
        };
        VerificationInput: {
            token: string;
        };
        VerificationRequired: {
            /** @constant */
            requiresVerification: true;
            message: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
        };
        AuthSession: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["AuthUser"];
        };
        SupportSession: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "support" | "super_admin";
        };
        Profile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            timezone: string;
            /** Format: date-time */
            suspended_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            onboarding_completed_at?: string | null;
            goal_preferences?: components["schemas"]["GoalPreference"][];
            starting_pace?: components["schemas"]["StartingPace"];
            religion_preference?: components["schemas"]["ReligionPreference"];
            daily_digest_time?: string;
            daily_digest_enabled?: boolean;
            latitude?: number | string | null;
            longitude?: number | string | null;
            madhab?: components["schemas"]["Madhab"] | null;
            prayer_calculation_method?: components["schemas"]["PrayerCalculationMethod"] | null;
            prayer_reminders?: {
                prayer_name: components["schemas"]["PrayerName"];
                enabled: boolean;
                offset_minutes: number;
            }[];
            push_enabled?: boolean;
        } & {
            [key: string]: unknown;
        };
        Frequency: {
            /** @constant */
            kind: "daily";
        } | {
            /** @constant */
            kind: "weekly_target";
            target: number;
        } | {
            /** @constant */
            kind: "weekdays";
            days: number[];
        };
        OnboardingInput: {
            name: string;
            /** @enum {string} */
            units: "metric" | "imperial";
            goals: components["schemas"]["GoalPreference"][];
            pace: components["schemas"]["StartingPace"];
            religion: components["schemas"]["ReligionPreference"];
            dailyDigestTime: string;
            dailyDigestEnabled: boolean;
            prayerSetup: components["schemas"]["PrayerSetup"] | null;
            templateIds: string[];
        };
        CreateHabitInput: components["schemas"]["TemplateHabitInput"] | components["schemas"]["CustomHabitInput"];
        TemplateHabitInput: {
            /** Format: uuid */
            templateId: string;
        };
        CustomHabitInput: {
            name: string;
            icon: string;
            /** @enum {string} */
            category: "diet" | "prayer" | "steps" | "gym" | "food" | "learning" | "other";
            /** @enum {string} */
            type: "do" | "avoid" | "count" | "duration";
            target?: number | null;
            unit?: string | null;
            frequency: components["schemas"]["Frequency"];
            /** @default false */
            forgiving: boolean;
        };
        CheckInInput: {
            /** @enum {string} */
            status: "done" | "skipped" | "partial";
            value?: number | null;
            note?: string | null;
            /** @enum {string|null} */
            prayerStatus?: "on_time" | "late" | "missed" | null;
        };
        Habit: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            name: string;
            icon: string;
            category: string;
            /** @enum {string} */
            habit_type: "do" | "avoid" | "count" | "duration";
            target?: number | null;
            unit?: string | null;
            frequency: components["schemas"]["Frequency"];
            /** @enum {string} */
            state: "active" | "paused" | "archived";
            reminder_enabled?: boolean;
            reminder_time?: string | null;
        } & {
            [key: string]: unknown;
        };
        HabitTemplate: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name: string;
            description?: string;
            icon: string;
            category: string;
            /** @enum {string} */
            habit_type: "do" | "avoid" | "count" | "duration";
            active?: boolean;
            goal_tags?: components["schemas"]["GoalPreference"][];
            recommendation_priority?: number;
        } & {
            [key: string]: unknown;
        };
        HabitLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            habit_id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: date */
            local_date: string;
            /** @enum {string} */
            status: "done" | "skipped" | "partial";
            value?: number | null;
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        NotificationDelivery: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            channel: "push" | "email" | "in_app";
            title: string;
            body: string;
            /** @enum {string} */
            state: "scheduled" | "processing" | "sent" | "failed" | "cancelled";
            /** Format: date-time */
            scheduled_at: string;
        } & {
            [key: string]: unknown;
        };
        AnnouncementInput: {
            title: string;
            body: string;
            channels: ("push" | "email" | "in_app")[];
        };
        ErrorEnvelope: {
            code: string;
            message: string;
            correlationId: string;
            retryable: boolean;
            fieldErrors?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        GoalPreference: "movement" | "nutrition" | "learning" | "sleep" | "mindfulness";
        /** @enum {string} */
        StartingPace: "light" | "balanced" | "ambitious";
        /** @enum {string} */
        ReligionPreference: "muslim" | "other" | "unspecified";
        /** @enum {string} */
        Madhab: "hanafi" | "shafi" | "maliki" | "hanbali";
        /** @enum {string} */
        PrayerCalculationMethod: "karachi" | "muslim_world_league" | "egyptian" | "umm_al_qura" | "dubai" | "qatar" | "kuwait" | "moonsighting_committee" | "singapore" | "turkey" | "tehran" | "north_america";
        /** @enum {string} */
        PrayerName: "fajr" | "dhuhr" | "asr" | "maghrib" | "isha";
        PrayerReminder: {
            prayer: components["schemas"]["PrayerName"];
            enabled: boolean;
            offsetMinutes: number;
        };
        PrayerSetup: {
            latitude: number;
            longitude: number;
            timezone: string;
            madhab: components["schemas"]["Madhab"];
            calculationMethod: components["schemas"]["PrayerCalculationMethod"];
            reminders: components["schemas"]["PrayerReminder"][];
        };
        RecommendationInput: {
            goals: components["schemas"]["GoalPreference"][];
            pace: components["schemas"]["StartingPace"];
        };
        PreferencesInput: {
            goals: components["schemas"]["GoalPreference"][];
            pace: components["schemas"]["StartingPace"];
            religion: components["schemas"]["ReligionPreference"];
            dailyDigestTime: string;
            dailyDigestEnabled: boolean;
            prayerSetup: components["schemas"]["PrayerSetup"] | null;
        };
        PrayerSchedule: {
            /** Format: date */
            date: string;
            timezone: string;
            madhab: components["schemas"]["Madhab"];
            calculationMethod: components["schemas"]["PrayerCalculationMethod"];
            prayers: {
                name: components["schemas"]["PrayerName"];
                /** Format: date-time */
                time: string;
                /** @enum {string|null} */
                status: "on_time" | "late" | "missed" | null;
            }[];
            nextPrayer: {
                name: components["schemas"]["PrayerName"];
                /** Format: date-time */
                time: string;
            } | null;
        };
        PrayerCheckInInput: {
            /** @enum {string} */
            status: "on_time" | "late" | "missed";
        };
        PrayerLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: date */
            local_date: string;
            prayer_name: components["schemas"]["PrayerName"];
            /** @enum {string} */
            status: "on_time" | "late" | "missed";
        };
        HabitReminderInput: {
            /** @constant */
            enabled: true;
            time: string;
        } | {
            /** @constant */
            enabled: false;
            time?: null | string;
        };
        FirebaseInstallationInput: {
            installationId: string;
            /**
             * @default web
             * @constant
             */
            platform: "web";
        };
    };
    responses: {
        /** @description Consistent error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        HabitId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupInput"];
            };
        };
        responses: {
            /** @description Verification email requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationRequired"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailInput"];
            };
        };
        responses: {
            /** @description Verification email requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationRequired"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationInput"];
            };
        };
        responses: {
            /** @description Email verified and session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Authenticated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["AuthUser"];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        loggedOut: true;
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingInput"];
            };
        };
        responses: {
            /** @description Onboarding completed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        completed: true;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listHabitTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitTemplate"][];
                };
            };
        };
    };
    listHabits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's habits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Habit"][];
                };
            };
        };
    };
    createHabit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHabitInput"];
            };
        };
        responses: {
            /** @description Created habit. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Habit"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getToday: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Habits due for the selected local date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["Habit"] & {
                        todayLog?: components["schemas"]["HabitLog"] | null;
                    })[];
                };
            };
        };
    };
    checkInHabit: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                habitId: components["parameters"]["HabitId"];
                localDate: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInInput"];
            };
        };
        responses: {
            /** @description Idempotent daily log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitLog"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's in-app notifications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDelivery"][];
                };
            };
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized support or super-admin session. */
            200: {
                headers: {
                    "Cache-Control"?: "private, no-store, max-age=0";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportSession"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Support user search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Profile"][];
                        count: number;
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    suspended: boolean;
                };
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminListTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All habit templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateTemplate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitTemplate"];
            };
        };
        responses: {
            /** @description Created template. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    adminUpdateTemplate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent notification deliveries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminRetryNotification: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification queued for retry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateAnnouncement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementInput"];
            };
        };
        responses: {
            /** @description Announcement queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Basic usage analytics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protected integration and queue health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListAuditLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent audit records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHabitRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationInput"];
            };
        };
        responses: {
            /** @description Ranked habit recommendations. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitTemplate"][];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesInput"];
            };
        };
        responses: {
            /** @description Preferences updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        updated?: true;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getPrayerTimes: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calculated prayer schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrayerSchedule"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    checkInPrayer: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                prayer: components["schemas"]["PrayerName"];
                localDate: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrayerCheckInInput"];
            };
        };
        responses: {
            /** @description Prayer check-in saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrayerLog"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    updateHabitReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: components["parameters"]["HabitId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitReminderInput"];
            };
        };
        responses: {
            /** @description Habit reminder updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enabled: boolean;
                        time: string | null;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    registerFirebaseInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirebaseInstallationInput"];
            };
        };
        responses: {
            /** @description Firebase installation registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        registered?: true;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    unregisterFirebaseInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                installationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firebase installation deactivated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        unregistered?: true;
                    };
                };
            };
        };
    };
}
